version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition.py
        --output output/input.arrow
        --dummy-data-file lib/dummydata/dummyinput.arrow
    outputs:
      highly_sensitive:
        cohort: output/input.arrow

  # describe:
  #   run: r:latest analysis/report.R
  #   needs: [generate_dataset]
  #   outputs: 
  #     moderately_sensitive:
  #       cohort: output/descriptive.png