version: '3.0'

expectations:
  population_size: 1000

actions:

  # generate_dummy_data:
  #   run: r:latest analysis/dummy_data_adults.R
  #   outputs:
  #     highly_sensitive:
  #       cohort: lib/dummydata/dummyinput.arrow

  generate_dataset:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition.py
        --output output/input.arrow
        --dummy-data-file lib/dummydata/dummyinput.arrow
    outputs:
      highly_sensitive:
        cohort: output/input.arrow
        
  summarise_dataset:
    run: python:latest analysis/summarise_dataset.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        cohort: output/summary.txt
        
  manipulate_dataset:
    run: r:latest analysis/data_manipulation.R
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        cohort: output/input_manipulated.arrow

  # describe:
  #   run: r:latest analysis/report.R
  #   needs: [generate_dataset, manipulate_dataset]
  #   outputs: 
  #     moderately_sensitive:
  #       cohort: output/descriptive.png